enum ResourceType{
  ActionGroup
  AksCluster
  AppInsights
  AppServicePlan
  CosmosDBAccount
  CosmosDBGremlinDatabase
  CosmosDBMongoDBDatabase
  CosmosDBSqlDatabase
  ContainerRegistry
  DataFactory
  DataFactoryLinkedService
  EventHub
  EventHubConsumerGroup
  EventHubNamespace
  KeyVault
  ResourceGroup
  SqlDatabase
  SqlServer
  StorageAccount
  StorageContainer
  SynapseSparkPool
  SynapseSqlPool
  SynapseWorkspace
  VirtualMachine
  WebApp
}
