enum ResourceType{
  ActionGroup
  AksCluster
  AksNodePool
  ApiManagement
  ApiManagementApi
  ApiManagementDiagnostic
  ApiManagementLogger
  ApiManagementPolicy
  AppInsights
  AppServicePlan
  ContainerApp
  ContainerAppManagedEnv
  CosmosDBAccount
  CosmosDBGremlinDatabase
  CosmosDBMongoDBDatabase
  CosmosDBSqlDatabase
  CosmosDBSqlRoleAssignment
  CosmosDBSqlRoleDefinition
  ContainerRegistry
  DataFactory
  DataFactoryLinkedService
  DiagnosticSetting
  EventHub
  EventHubConsumerGroup
  EventHubNamespace
  KeyVault
  KeyVaultCertificate
  KeyVaultKey
  KeyVaultSecret
  OperationalInsightsWorkspace
  PortalDashboard
  ResourceGroup
  RoleAssignment
  SqlDatabase
  SqlServer
  StorageAccount
  StorageContainer
  StreamAnalyticsCluster
  StreamAnalyticsFunction
  StreamAnalyticsInput
  StreamAnalyticsJob
  StreamAnalyticsOutput
  StreamAnalyticsTransformation
  SynapseSparkPool
  SynapseSqlPool
  SynapseWorkspace
  VirtualMachine
  WebApp
  WebAppStaticSite
}
