enum ResourceType{
  ActionGroup
  AksCluster
  AksNodePool
  ApiManagement
  ApiManagementApi
  ApiManagementDiagnostic
  ApiManagementLogger
  ApiManagementPolicy
  AppInsights
  AppServicePlan
  ContainerApp
  CosmosDBAccount
  CosmosDBGremlinDatabase
  CosmosDBMongoDBDatabase
  CosmosDBSqlDatabase
  ContainerRegistry
  DataFactory
  DataFactoryLinkedService
  EventHub
  EventHubConsumerGroup
  EventHubNamespace
  KeyVault
  OperationalInsightsWorkspace
  ResourceGroup
  RoleAssignment
  SqlDatabase
  SqlServer
  StorageAccount
  StorageContainer
  StreamAnalyticsCluster
  StreamAnalyticsFunction
  StreamAnalyticsInput
  StreamAnalyticsJob
  StreamAnalyticsOutput
  StreamAnalyticsTransformation
  SynapseSparkPool
  SynapseSqlPool
  SynapseWorkspace
  VirtualMachine
  WebApp
}
