---
APPLY_FIXES: none  # all, none, or list of linter keys
FILTER_REGEX_EXCLUDE: (BenchPress/bicep)
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
LINTER_RULES_PATH: .github/config/linter
CSHARP_DOTNET_FORMAT_PRE_COMMANDS:
  - command: cd BenchPress
