---
APPLY_FIXES: none # all, none, or list of linter keys
FILTER_REGEX_EXCLUDE: (BenchPress/bicep)
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
  - REPOSITORY_GIT_DIFF
  - CSHARP_DOTNET_FORMAT
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM
POWERSHELL_POWERSHELL_FILTER_REGEX_EXCLUDE: (BenchPress/Generators/templates/)
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (.vscode/)
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
LINTER_RULES_PATH: .github/config/linter
# CSHARP_DOTNET_FORMAT_ARGUMENTS: /BenchPress/BenchPress.sln --exclude ./BenchPress/bicep/
# CSHARP_DOTNET_FORMAT_PRE_COMMANDS:
#   - command: git submodule update --init --recursive
#     cwd: "workspace"
#   - command: dotnet restore BenchPress
#     cwd: "workspace"
