# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS: 
  - PYTHON_PYRIGHT
  - PYTHON_MYPY
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
FILTER_REGEX_EXCLUDE: '(\./node_modules)'
EXCLUDED_DIRECTORIES: ["node_modules", ".git"]
PRINT_ALPACA: false
EMAIL_REPORTER: false
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM
  # - PYTHON_BANDIT # consider disabling?  disabled for the megalinter project itself
PARALLEL: true
IGNORE_GITIGNORED_FILES: true
GITHUB_STATUS_REPORTER: true
MARKDOWN_DEFAULT_STYLE: markdownlint
VALIDATE_ALL_CODEBASE: true # Will parse the entire repository and find all files to validate across all types. NOTE: When set to false, only new or edited files will be parsed for validation.
SHOW_SKIPPED_LINTERS: true
PRINT_ALL_FILES: true
PYTHON_PYLINT_CONFIG_FILE: /config/megalinter/.pylintrc
SPELL_CSPELL_CONFIG_FILE: /config/megalinter/.cspell.json
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: /config/megalinter/.markdown-link-check.json
COPYPASTE_JSCPD_CONFIG_FILE: /config/megalinter/.jscpd.json
DOCKERFILE_HADOLINT_CONFIG_FILE: /config/megalinter/.hadolint
EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: /config/megalinter/.ecrc
JSON_JSONLINT_CONFIG_FILE: /config/megalinter/.jsonlintrc
JAVASCRIPT_PRETTIER_CONFIG_FILE: /config/megalinter/.prettierrc.json
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: /config/megalinter/.markdownlint.json
POWERSHELL_POWERSHELL_CONFIG_FILE: /config/megalinter/.powershell-psscriptanalyzer.psd1
# BICEP_BICEP_LINTER doesn't source a file from a specific path, but a relative path to where a bicep file is invoked..
# YAML_V8R: .v8rrc # this file needs to be in the root directory, v8r doesn't provide a config file path param, perhaps create PR again v8r?
REPOSITORY_SECRETLINT_CONFIG_FILE: /config/megalinter/.secretlintrc.json
REPOSITORY_SYFT_CONFIG_FILE: /config/megalinter/.syft.yaml
JSON_ESLINT_PLUGIN_JSONC_CONFIG_FILE: /config/megalinter/.eslintrc-json.json
ARM_ARM_TTK_CONFIG_FILE: /config/megalinter/.arm-ttk.psd1
ACTION_ACTIONLINT_CONFIG_FILE: /config/megalinter/actionlint.yml
REPOSITORY_CHECKOV_CONFIG_FILE: /config/megalinter/.checkov.yml
# PYTHON_PYRIGHT_CONFIG_FILE: /config/megalinter/pyrightconfig.json # DISABLED
PYTHON_MYPY_CONFIG_FILE: /config/megalinter/.mypy.ini
PYTHON_FLAKE8_CONFIG_FILE: /config/megalinter/.flake8
PYTHON_BLACK_CONFIG_FILE: /config/megalinter/pyproject.toml
PYTHON_BANDIT_CONFIG_FILE: /config/megalinter/.bandit.yml
REPOSITORY_GITLEAKS_CONFIG_FILE: /config/megalinter/.gitleaks.toml