# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS: 
  - PYTHON_PYRIGHT
  - PYTHON_MYPY
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
FILTER_REGEX_EXCLUDE: '(\./node_modules)'
EXCLUDED_DIRECTORIES: ["node_modules", ".git"]
PRINT_ALPACA: false
EMAIL_REPORTER: false
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM
  # - PYTHON_BANDIT # consider disabling?  disabled for the megalinter project itself
PARALLEL: true
IGNORE_GITIGNORED_FILES: true
GITHUB_STATUS_REPORTER: true
MARKDOWN_DEFAULT_STYLE: markdownlint
VALIDATE_ALL_CODEBASE: true # Will parse the entire repository and find all files to validate across all types. NOTE: When set to false, only new or edited files will be parsed for validation.
SHOW_SKIPPED_LINTERS: true
PRINT_ALL_FILES: true
LINTER_RULES_PATH: /config/megalinter/

