---
APPLY_FIXES: none # all, none, or list of linter keys
FILTER_REGEX_EXCLUDE: (BenchPress/bicep)
DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
  - REPOSITORY_GIT_DIFF
  - CSHARP_DOTNET_FORMAT
  - ACTION_ACTIONLINT
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
LINTER_RULES_PATH: .github/config/linter
POWERSHELL_POWERSHELL_FILTER_REGEX_EXCLUDE: (.*/Generators/templates/|.*/BenchPress.Azure/Bicep.psm1)
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (.vscode/)
