---
name: "Publish and test demo app"
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare required variables
        shell: pwsh
        run: |
          # Set the ENVIRONMENT_SUFFIX to a random value
          # This will be used to create a unique resource group name
          $env:ENVIRONMENT_SUFFIX = (Get-Random).ToString("x8")

          # Set the location to westus2
          $env:LOCATION = "westus2"

      - name: Login via az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Installing Az module
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force

      - name: Deploy infrastructure and demo app
        shell: pwsh
        working-directory: ./assets/demos
        run: |
          ./deploy-demoapp.ps1

      - name: Run the tests
        shell: pwsh
        working-directory: ./assets/demos
        env:
          AZ_TENANT_ID: ${{secrets.AZ_TENANT_ID}}
          AZ_SUBSCRIPTION_ID: ${{secrets.AZ_SUBSCRIPTION_ID}}
          AZ_APPLICATION_ID: ${{secrets.AZ_APPLICATION_ID}}
          AZ_ENCRYPTED_PASSWORD: ${{secrets.AZ_ENCRYPTED_PASSWORD}}
        run: |
          ./DemoApp.Tests.ps1

      - name: Clean up resources
        shell: pwsh
        run: |
          az group delete --name "benchpress-rg-${env:ENVIRONMENT_SUFFIX}" --yes
