---
# yamllint disable line-length
name: "Publish and test demo app"
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare required variables
        shell: pwsh
        run: |
          # Set the ENVIRONMENT_SUFFIX to a random value
          # This will be used to create a unique resource group name
          $env:ENVIRONMENT_SUFFIX = (Get-Random).ToString("x8")

          # Set the location to westus2
          $env:LOCATION = "westus2"

      - name: Deploy infrastructure and demo app
        shell: pwsh
        run: |
          ./deploy-demoapp.ps1

      - name: Run the tests
        shell: pwsh
        run: |
          ./DemoApp.Tests.ps1

      - name: Clean up resources
        shell: pwsh
        run: |
          az group delete --name "benchpress-rg-${env:ENVIRONMENT_SUFFIX}" --yes
