---
name: cd-create-version-tag

on: #  yamllint disable-line rule:truthy
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  create-version-tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'version')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TESTPATTOKEN }}
      - name: Retrieve Version and Create Version Tag
        # I don't know why, but the first sed command adds a space to the beginning of the string so the second sed
        # command removes that space.
        # This will create a version tag with a leading "v" followed by the ModuleVersion value inside the quotes
        # e.g., "v0.1" for ModuleVersion = "0.1"
        run: |
          cd ./Modules/BenchPress.Azure
          version=v$(sed -n 's/ModuleVersion = "\([^"]*\)"/\1/p' ./BenchPress.Azure.psd1 \
            | sed -n 's/\s*//p')
          git tag "$version"
          git push origin "$version"
