---
name: cd-github-release

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v[0-9]+.[0-9]+*"

jobs:
  deploy:
    if: github.event.base_ref == "refs/heads/main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub Release for BenchPress Module
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: "./BenchPress/Helpers/Azure/*"
          generateReleaseNotes: true
          makeLatest: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
