---
name: cd-psgallery

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  publish-to-gallery:
    name: Publish to the PowerShell Gallery
    runs-on: ubuntu-latest
    steps:
      - name: Download module artifacts
        uses: actions/download-artifact@v3
        with:
          name: benchpress-gallery-module
          path: ./bin
      - name: Publish BenchPress to Gallery
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path ./bin -NugetAPIKey $env:NUGET_KEY -Verbose
