---
name: ci-module-versioning

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - "Modules/BenchPress.Azure/**"

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      Version: ${{ steps.gitversion.outputs.majorMinorPatch }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.x"
      - name: Checkout Latest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion

  update-manifest:
    needs: [get-tags]
    if: needs.get-tags.outputs.CommitsSinceVersionSource > 0
    runs-on: ubuntu-latest
    steps:
      - name: Create and checkout new version branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git checkout -b version
      - name: Update manifest file
        run: |
          sed -i 's/ModuleVersion = "[^"]*"/ModuleVersion = "${{ needs.get-tags.outputs.Version }}"/' \
            ./Modules/BenchPress.Azure/BenchPress.Azure.psd1
      - name: Commit changes and create pull request
        run: |
          git add ./Modules/BenchPress.Azure/BenchPress.Azure.psd1
          git commit -m "version: updating version"
          git push origin version
          gh pr create -B main -H version --title 'Merge updated version for manifest file into main.' \
            --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
