---
name: ci-module-versioning

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - './BenchPress/Helpers/BenchPress.Azure/*'

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      Version: ${{ steps.gitversion.outputs.majorMinorPatch }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'
      - name: Checkout Latest
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion

  update-manifest:
    needs: [get-tags]
    if: needs.get-tags.output.CommitsSinceVersionSource > 0
    runs-on: ubuntu-latest
    steps:
      - name: Create and checkout new version branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b version
      - name: Update manifest file
        needs: [get-tags]
        run: |
          sed -i 's/ModuleVersion = "[^"]*"/ModuleVersion = "${{ needs.get-tags.output.Version }}"/' \
            ./BenchPress/Helpers/BenchPress.Azure/BenchPress.Azure.psd1
      - name: Commit Changes
        run: |
          git add ./BenchPress/Helpers/BenchPress.Azure/BenchPress.Azure.psd1
          git commit -m "version: updating version"
          git push origin version
