---
name: "Publish docs branch"

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - "./BenchPress/Helpers/BenchPress.Azure/*.psm1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish-docs-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: docs
          token: ${{ secrets.DOCS_ACTION_TOKEN }}

      - name: Install Platyps
        shell: pwsh
        run: |
          Install-Module -Name platyPS -Scope CurrentUser -Force
          Import-Module platyPS

      - name: Create and checkout new docs branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b docs

      - name: Generate docs
        shell: pwsh
        run: |
          Import-Module ./BenchPress/Helpers/BenchPress.Azure/BenchPress.Azure.psd1
          Import-Module ../scripts/generate-docs-workflow.psm1

          # Create the docs/helpers folder if it doesn't exist
          New-Item -ItemType Directory -Path "./docs/helpers" -Force

          # Generate the markdown files
          New-MarkdownHelp -Module BenchPress.Azure -OutputFolder ./docs/helpers -Force -AlphabeticParamsOrder -UseFullTypeName -NoMetadata

          # Ensure the generated markdown files are in the correct format
          Format-AutoGeneratedMarkdownFiles -Version ${{ github.sha }}

      - name: If there are changes push the branch
        run: |
          if [ "$(git ls-files --deleted --modified --others --exclude-standard -- ./docs | wc -l)" -gt 0 ]
          then
            git add docs
            git commit -m "docs: updating generated documentation"
            git push origin docs
          fi
