---
name: "Publish Docs branch"
on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - "./BenchPress/Helpers/BenchPress.Azure/*.psm1"

jobs:
  publish-docs-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Platyps
        shell: pwsh
        run: |
          Install-Module -Name platyPS -Scope CurrentUser -Force
          Import-Module platyPS

      - name: Create and checkout new docs branch
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b docs

      - name: Generate docs
        shell: pwsh
        run: |
          Import-Module ./BenchPress/Helpers/BenchPress.Azure/BenchPress.Azure.psd1
          New-MarkdownHelp -Module BenchPress.Azure -OutputFolder ./docs

      - name: If there are changes push the branch
        run: |
          if [ "$(git ls-files --deleted --modified --others --exclude-standard -- ./docs | wc -l)" -gt 0 ]
          then
            git add docs
            git commit -m "docs: updating generated documentation"
            git push origin docs
          fi
