---
name: ci
on: # yamllint disable-line rule:truthy
  push:
    branches: [main]

jobs:
  build-benchpress:
    name: Build .NET solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Initialize Bicep Submodule
        run: git submodule update --init --recursive
      - name: Build Benchpress Solution
        working-directory: BenchPress
        run: dotnet build
  build-modules:
    name: Build the PS Gallery Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Build Module Files
        shell: pwsh
        run: |
          ./build.ps1 -InLine
      - name: Archive Module artifacts
        uses: actions/upload-artifact@v3
        with:
          name: benchpress-gallery-module
          path: |
            ./bin/BenchPress.Azure.psd1
            ./bin/BenchPress.Azure.psm1
  local-psgallery:
    name: Publish and import from/to local PSGallery
    runs-on: ubuntu-latest
    steps:
      - name: Create the local PSGallery folder
        shell: pwsh
        run: |
          $path = New-Item -Path ./packages -ItemType Directory
          Register-PSRepository -Name LocalFeedPSRepo -SourceLocation $path.ToString() `
            -PublishLocation $path.ToString() -InstallationPolicy Trusted
      - name: Download module artifacts
        uses: actions/download-artifact@v3
        with:
          name: benchpress-gallery-module
          path: ./module
      - name: Publish AzBP Module
        shell: pwsh
        run: |
          Publish-Module -Path ./module -Repository LocalFeedPSRepo -Verbose
      - name: Install AzBP Module from the repository
        shell: pwsh
        run: |
          Install-Module BenchPress.Azure
      - name: Verify module exposes cmdlets (smoke test)
        shell: pwsh
        run: |
          if ($(Get-Module -Name BenchPress.Azure -ListAvailable).ExportedCommands.Count -eq 0)
          {
            throw "No commands are available in the BenchPress.Azure Module."
          }
