---
name: pr-bicep
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/pr-bicep.yml'
      - '**.bicep'

jobs:
  lint-bicep:
    name: Lint Bicep Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3

      - name: Lint Bicep Files
        shell: pwsh
        run: |
          Get-ChildItem -Path './' -Filter '*.bicep' -Recurse | ForEach-Object { az bicep build -f $_ }
