---
name: pr-dotnet
on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/pr-dotnet.yml"
      - "BenchPress/**"

jobs:
  run-unit-tests:
    name: Run .NET Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Initialize Bicep Submodule
        run: git submodule update --init --recursive
      - name: Run Unit Tests
        working-directory: BenchPress
        run: dotnet test
      - name: Archive Unit Test Results
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-results
          path: BenchPress/dotnet-test-results.xml
