---
name: pr-yaml
on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/pr-yaml.yml"
      - "**.yml"
      - "**.yaml"

env:
  LINTER_CONFIG_DIR: ./.github/config/linter

jobs:
  lint-yaml:
    name: Lint YAML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3

      - name: Lint YAML Files
        run: |
          pip install yamllint
          yamllint . --config-file "$LINTER_CONFIG_DIR/.yamllint.yml"
