name: pr_dotnet

on:
  pull_request:
    paths:
      - "framework/dotnet/**"
      - "samples/dotnet/**"
      - "engine/**"
      - "protos/**"
      - ".github/workflows/pr_dotnet.yaml"
    branches:
      - main

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  lint:
    name: lint-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: MegaLinter dotnet flavor
        uses: oxsecurity/megalinter/flavors/dotnet@v6.12.0
        env:
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true
          PRINT_ALL_FILES: true
          DISABLE: SPELL,COPYPASTE,YAML
          DISABLE_LINTERS: REPOSITORY_CHECKOV,REPOSITORY_TRIVY
          FILTER_REGEX_EXCLUDE: '(BenchPress/|examples/|/docs|\.devcontainer|\.editorconfig|\.gitmodules|\.sln|\.md|LICENSE|/framework/python|samples/python)'
          FILTER_REGEX_INCLUDE: '(framework/dotnet|samples/dotnet|engine/)'
          REPORT_OUTPUT_FOLDER: ${GITHUB_WORKSPACE}/megalinter-reports

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
