name: "Publish Docs"
on:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Platyps
        shell: pwsh
        run: |
          Install-Module -Name platyPS -Scope CurrentUser -Force

      - name: Generate docs
        shell: pwsh
        run: |
          Import-Module platyPS
          cd ./BenchPress/Helpers/Azure/
          Import-Module ./BenchPress.Azure.psd1
          New-MarkdownHelp -Module BenchPress.Azure -OutputFolder ..\..\..\docs

      - name: Publish changes to docs branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b docs
          git add docs
          git commit -m "docs: updating docs"
          git push origin docs
